### ISSUE TITLE
Suggest to add a function to convert from `float Scalar.t` to `float`

### ISSUE THREAD

**Issue by arbipher** [janestreet/torch#11]
It's easy to put an OCaml primitive value into `Scalar` e.g. `Scalar.float: float -> float Scalar.t`.
However, I don't figure out a simple way to unbox it.

A workaround is using a Tensor as an intermediate step but it doesn't look elegant.
`let float_of_scalar s = Tensor.(add_scalar (zeros [ 1 ]) s |> float_value)`.

**Comment by mwlon** [comment]
This would be nice to add. Would you be able to make a pull request for this?

**Comment by arbipher** [comment]
Sure. ~~Let me seek some time in this weekend.~~

Here it is #12
