### ISSUE TITLE
Current master fails to build

### ISSUE THREAD

**Issue by darioteixeira** [janestreet/torch#8]
I've tried to compile this repo's current master (https://github.com/janestreet/torch/commit/b1ee8db5c9aa150d76a9b24dbb55f1c79cfd3655) using OCaml 4.14.1 on an AMD64 system running (K)ubuntu 23.10. I've used what the README refers to as "Option 3" for installation, ie, using the system libraries. The corresponding distro packages are libtorch-dev (version 2.0.1+dfsg-4) and libtorch2.0:amd64 (version 2.0.1+dfsg-4). Note that therefore the OPAM package libtorch is not installed.

The compilation fails with the following error:

```
torch_api_generated.cpp.h: In function ‘void atg_var_mean_correction_out(at::Tensor**, tensor, tensor, tensor, int64_t*, int, scalar, int)’:
torch_api_generated.cpp.h:18062:174: error: could not convert ‘* correction’ from ‘c10::Scalar’ to ‘c10::optional<long int>’
18062 |     auto outputs__ = torch::var_mean_out(*out0, *out1, *self, dim_data == nullptr ? c10::nullopt : c10::optional<torch::IntArrayRef>(torch::IntArrayRef(dim_data, dim_len)), *correction, (bool)keepdim);
      |                                                                                                                                                                              ^~~~~~~~~~~
      |                                                                                                                                                                              |
      |                                                                                                                                                                              c10::Scalar
torch_api.h:15:5: note: in definition of macro ‘PROTECT’
   15 |     x                                                                          \
      |     ^
```

Also, I'm a bit puzzled by the inclusion of file [third_party/pytorch/Declarations-v1.13.0.yaml](https://github.com/janestreet/torch/blob/master/third_party/pytorch/Declarations-v1.13.0.yaml) in the repo, even though [src/gen/gen.ml](https://github.com/janestreet/torch/blob/master/src/gen/gen.ml) references `third_party/pytorch/Declarations-v2.1.0.yaml`.

**Comment by mwlon** [comment]
This is a documentation mistake on our side:
* The current version uses 2.1. We actually fixed this internally weeks ago, but our cycle to update the public repo is pretty slow.
* The content in declarations isn't necessarily what we used. I'll remove the declarations file and update the documentation to be clearer.

So for now, can you retry with 2.1 installed?

**Comment by darioteixeira** [comment]
Thank you for your reply, @mwlon. I have tried compiling it against Pytorch 2.1.2, and can confirm that it works!

**Comment by darioteixeira** [comment]
I'm closing this issue, since compilation against Pytorch 2.1.2 succeeds.
