### ISSUE TITLE
`v0.17~preview.129.07+242` fails to build

### ISSUE THREAD

**Issue by arbipher** [janestreet/torch#9]
I can build the previous version `v0.17~preview.129.00+111` with either the `libtorch` on opam or my custom torch library. But there are a few problems with the latest `v0.17~preview.129.07+242`.

1. `npy` listed in the `bin/dune` is not public. The one I can find `https://github.com/LaurentMazare/npy-ocaml` doesn't have module `Npy_lib` which `bin/tensor_tools.ml` will include.

I can pass the problem by commenting this dune file.

2. Missing header file

```shell
File "src/wrapper/dune", line 4, characters 9-18:
4 |   (names torch_api)
             ^^^^^^^^^
torch_api.cpp:1:10: fatal error: torch/csrc/autograd/engine.h: No such file or directory
    1 | #include <torch/csrc/autograd/engine.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

This doesn't look like a fresh [question](https://github.com/LaurentMazare/tch-rs/issues/222).  

It can be solved by `set LIBTORCH_INCLUDE /path/to/torch/include` (also need to set `LIBTORCH`).

3. When both `LIBTORCH` and `LIBTORCH_INCLUDE` are set, they report on `so` files missing but I do have them.

```shell
$ dune build
File "src/wrapper/dune", line 1, characters 0-379:
 1 | (library
 2 |  (foreign_stubs
 3 |   (language cxx)
....
18 |  (libraries ctypes.foreign ctypes.stubs ctypes)
19 |  (preprocess
20 |   (pps ppx_jane)))
/usr/bin/ld: cannot find -l/home/ex/.opam/5.1.1/lib/libtorch/lib/libc10.so: No such file or directory
/usr/bin/ld: cannot find -l/home/ex/.opam/5.1.1/lib/libtorch/lib/libtorch_cpu.so: No such file or directory
/usr/bin/ld: cannot find -l/home/ex/.opam/5.1.1/lib/libtorch/lib/libtorch.so: No such file or directory
collect2: error: ld returned 1 exit status
```

I am unclear about this error. I tried both `libtorch=2.1.2+linux-x86_64` on opam or my custom torch. The error message is the same.

```shell
$ ls /home/ex/.opam/5.1.1/lib/libtorch/lib/*.so
/home/ex/.opam/5.1.1/lib/libtorch/lib/libbackend_with_compiler.so*  /home/ex/.opam/5.1.1/lib/libtorch/lib/libtorchbind_test.so*
/home/ex/.opam/5.1.1/lib/libtorch/lib/libc10.so*                    /home/ex/.opam/5.1.1/lib/libtorch/lib/libtorch_cpu.so*
/home/ex/.opam/5.1.1/lib/libtorch/lib/libjitbackend_test.so*        /home/ex/.opam/5.1.1/lib/libtorch/lib/libtorch_global_deps.so*
/home/ex/.opam/5.1.1/lib/libtorch/lib/libnnapi_backend.so*          /home/ex/.opam/5.1.1/lib/libtorch/lib/libtorch_python.so*
/home/ex/.opam/5.1.1/lib/libtorch/lib/libshm.so*                    /home/ex/.opam/5.1.1/lib/libtorch/lib/libtorch.so*
```

**Comment by arbipher** [comment]
I am also unclear how about your jane street policy on PR from the outside. I read from other posts that you have an internal code repo that some of the problems may already be solved.

All the `dune` files in examples are missing and some examples cannot run e.g. `examples/mnist` ([`argmax`](https://github.com/janestreet/torch/blob/3aa49efabe26fa622bfe54a571cf140704485630/src/torch/dataset_helper.ml#L165) will trigger a dimension mismatch fatal error).

**Comment by mwlon** [comment]
Thanks for reporting this. I'll try to ensure this gets fixed before we release v0.17.

If you make a PR, we'll review, changes will be applied internally, the PR will be closed instead of merged, and eventually the changes will surface to Github. Will you be able to make a PR for this?

The argmax issue is probably a secondary bug that came up after we fixed some broken reduction behavior: https://github.com/janestreet/torch/issues/6

**Comment by arbipher** [comment]
I see. Thanks for your explanation for RP. I think I can make it today to cover the trivial problems (just fixing 1 and adding the missing `dune` for all the runnable examples). For the building and linking problems 2&3, I don't have an immediate answer but I'll try if I can figure it out.

**Comment by arbipher** [comment]
I fixed the building problem in a follow-up commit 229046a in the same PR #10.

The fix is simple. It shouldn't use `-l/home/ex/.opam/5.1.1/lib/libtorch/lib/libc10.so`. (If `-L` is set correct) just `-lc10`.

It's almost to revert the change at `discover.ml` in 3aa49efabe26fa622bfe54a571cf140704485630. Also, no need to set `LIBTORCH_INCLUDE` because `discover.ml` has already computed that.

With the change in the PR, I can build and run with
1. empty `LIBTORCH`.
2. set `LIBTORCH` to a custom GPU shared library
3. set `LIBTORCH` to the opam-installed one.

**Comment by mwlon** [comment]
Yep - I've merged a fix for this internally now. It should get pushed out at some point.
